export CC=gcc
export RM=rm -f
export AR=ar cr
export MV=mv
export RANLIB=ranlib
export SED=sed


export SHELL=/bin/sh

INCFLAGS=-I. -I.. -I../include

CFLAGS=-O3 -w $(INCFLAGS) 
#Pentium 4 (Intel)
#CFLAGS=-march=pentium4 -O3 -pipe -fomit-frame-pointer $(INCFLAGS)
#Athlon XP (AMD)
#CFLAGS="-march=athlon-xp -O3 -pipe -fomit-frame-pointer" $(INCFLAGS)
#Athlon64£º
#CFLAGS="-O2 -march=athlon64 -ftracer -fprefetch-loop-arrays -pipe" $(INCFLAGS)

PROG=libmap.a

SRC=readmap.c map_deal.c map_util.c map_warppoint.c
OBJ=$(SRC:.c=.o)

ifeq (0,$(MAKELEVEL))
CC=gcc
RM=rm -f
AR=ar cr
MV=mv
RANLIB=ranlib
SED=sed
SHELL=/bin/sh
endif

all: $(PROG)

$(PROG): $(OBJ)
	$(RM) $(PROG)
	$(AR) $(PROG) $(OBJ)
	$(RANLIB) $(PROG)
	
dos2unix:
	dos2unix $(SRC) makefile

chmod:
	chmod 777 $(SRC) makefile
	
depend:
	$(MV) makefile makefile.bak
	$(SED) -ne '1,/^# DO NOT DELETE THIS LINE/p' makefile.bak>makefile
	$(CC) $(INCFLAGS) -M $(SRC) >> makefile 

clean:
	$(RM) $(PROG)
	$(RM) $(OBJ)
	$(RM) *~

distclean:
	$(RM) $(PROG)
	$(RM) $(OBJ)
	$(RM) *~
	$(MV) makefile makefile.bak
	$(SED) -ne '1,/^# DO NOT DELETE THIS LINE/p' makefile.bak>makefile
	$(RM) makefile.bak

# DO NOT DELETE THIS LINE
readmap.o: readmap.c ../include/version.h ../include/correct_bug.h \
  /usr/include/stdio.h /usr/include/_ansi.h /usr/include/newlib.h \
  /usr/include/sys/config.h /usr/include/machine/ieeefp.h \
  /usr/include/cygwin/config.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stddef.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stdarg.h \
  /usr/include/sys/reent.h /usr/include/_ansi.h /usr/include/sys/_types.h \
  /usr/include/sys/lock.h /usr/include/sys/types.h \
  /usr/include/machine/_types.h /usr/include/machine/types.h \
  /usr/include/sys/features.h /usr/include/cygwin/types.h \
  /usr/include/sys/sysmacros.h /usr/include/stdint.h \
  /usr/include/endian.h /usr/include/sys/stdio.h /usr/include/sys/cdefs.h \
  /usr/include/stdlib.h /usr/include/machine/stdlib.h \
  /usr/include/alloca.h /usr/include/cygwin/stdlib.h \
  /usr/include/cygwin/wait.h /usr/include/string.h \
  /usr/include/sys/string.h /usr/include/dirent.h \
  /usr/include/sys/dirent.h /usr/include/errno.h /usr/include/sys/errno.h \
  /usr/include/unistd.h /usr/include/sys/unistd.h /usr/include/getopt.h \
  /usr/include/netinet/in.h /usr/include/cygwin/in.h \
  /usr/include/cygwin/socket.h /usr/include/asm/socket.h \
  /usr/include/cygwin/if.h /usr/include/sys/socket.h \
  /usr/include/features.h /usr/include/sys/time.h \
  /usr/include/cygwin/sys_time.h /usr/include/sys/select.h \
  /usr/include/time.h /usr/include/machine/time.h \
  /usr/include/cygwin/time.h /usr/include/signal.h \
  /usr/include/sys/signal.h /usr/include/cygwin/signal.h \
  /usr/include/cygwin/sockios.h /usr/include/cygwin/uio.h \
  /usr/include/asm/byteorder.h /usr/include/sys/stat.h \
  /usr/include/cygwin/stat.h ../include/common.h ../include/object.h \
  ../include/common.h ../include/readmap.h ../include/util.h \
  ../include/buf.h ../include/util.h ../include/char.h \
  ../include/char_base.h ../include/version.h ../include/skill.h \
  ../include/title.h ../include/addressbook.h ../include/net.h \
  /usr/include/pthread.h /usr/include/sched.h ../include/char_data.h \
  ../include/item.h ../include/char.h ../include/lssproto_serv.h \
  ../include/lssproto_util.h /usr/include/strings.h \
  ../include/configfile.h
map_deal.o: map_deal.c ../include/version.h ../include/correct_bug.h \
  ../include/common.h /usr/include/stdio.h /usr/include/_ansi.h \
  /usr/include/newlib.h /usr/include/sys/config.h \
  /usr/include/machine/ieeefp.h /usr/include/cygwin/config.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stddef.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stdarg.h \
  /usr/include/sys/reent.h /usr/include/_ansi.h /usr/include/sys/_types.h \
  /usr/include/sys/lock.h /usr/include/sys/types.h \
  /usr/include/machine/_types.h /usr/include/machine/types.h \
  /usr/include/sys/features.h /usr/include/cygwin/types.h \
  /usr/include/sys/sysmacros.h /usr/include/stdint.h \
  /usr/include/endian.h /usr/include/sys/stdio.h /usr/include/sys/cdefs.h \
  /usr/include/errno.h /usr/include/sys/errno.h ../include/readmap.h \
  ../include/common.h ../include/util.h /usr/include/sys/time.h \
  /usr/include/cygwin/sys_time.h /usr/include/sys/select.h \
  /usr/include/time.h /usr/include/machine/time.h \
  /usr/include/cygwin/time.h /usr/include/signal.h \
  /usr/include/sys/signal.h /usr/include/cygwin/signal.h \
  /usr/include/stdlib.h /usr/include/machine/stdlib.h \
  /usr/include/alloca.h /usr/include/cygwin/stdlib.h \
  /usr/include/cygwin/wait.h ../include/char.h ../include/char_base.h \
  ../include/version.h ../include/skill.h ../include/title.h \
  ../include/addressbook.h ../include/net.h /usr/include/netinet/in.h \
  /usr/include/cygwin/in.h /usr/include/cygwin/socket.h \
  /usr/include/asm/socket.h /usr/include/cygwin/if.h \
  /usr/include/sys/socket.h /usr/include/features.h \
  /usr/include/cygwin/sockios.h /usr/include/cygwin/uio.h \
  /usr/include/asm/byteorder.h /usr/include/pthread.h \
  /usr/include/sched.h ../include/char_data.h ../include/item.h \
  ../include/char.h ../include/map_util.h ../include/lssproto_serv.h \
  ../include/lssproto_util.h /usr/include/string.h \
  /usr/include/sys/string.h /usr/include/strings.h /usr/include/unistd.h \
  /usr/include/sys/unistd.h /usr/include/getopt.h ../include/net.h \
  ../include/anim_tbl.h
map_util.o: map_util.c ../include/version.h ../include/correct_bug.h \
  ../include/common.h /usr/include/stdio.h /usr/include/_ansi.h \
  /usr/include/newlib.h /usr/include/sys/config.h \
  /usr/include/machine/ieeefp.h /usr/include/cygwin/config.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stddef.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stdarg.h \
  /usr/include/sys/reent.h /usr/include/_ansi.h /usr/include/sys/_types.h \
  /usr/include/sys/lock.h /usr/include/sys/types.h \
  /usr/include/machine/_types.h /usr/include/machine/types.h \
  /usr/include/sys/features.h /usr/include/cygwin/types.h \
  /usr/include/sys/sysmacros.h /usr/include/stdint.h \
  /usr/include/endian.h /usr/include/sys/stdio.h /usr/include/sys/cdefs.h \
  /usr/include/errno.h /usr/include/sys/errno.h ../include/char.h \
  ../include/common.h ../include/char_base.h ../include/version.h \
  ../include/skill.h ../include/util.h /usr/include/sys/time.h \
  /usr/include/cygwin/sys_time.h /usr/include/sys/select.h \
  /usr/include/time.h /usr/include/machine/time.h \
  /usr/include/cygwin/time.h /usr/include/signal.h \
  /usr/include/sys/signal.h /usr/include/cygwin/signal.h \
  /usr/include/stdlib.h /usr/include/machine/stdlib.h \
  /usr/include/alloca.h /usr/include/cygwin/stdlib.h \
  /usr/include/cygwin/wait.h ../include/title.h ../include/addressbook.h \
  ../include/net.h /usr/include/netinet/in.h /usr/include/cygwin/in.h \
  /usr/include/cygwin/socket.h /usr/include/asm/socket.h \
  /usr/include/cygwin/if.h /usr/include/sys/socket.h \
  /usr/include/features.h /usr/include/cygwin/sockios.h \
  /usr/include/cygwin/uio.h /usr/include/asm/byteorder.h \
  /usr/include/pthread.h /usr/include/sched.h ../include/char_data.h \
  ../include/item.h ../include/char.h ../include/readmap.h
map_warppoint.o: map_warppoint.c ../include/version.h \
  ../include/correct_bug.h /usr/include/string.h /usr/include/_ansi.h \
  /usr/include/newlib.h /usr/include/sys/config.h \
  /usr/include/machine/ieeefp.h /usr/include/cygwin/config.h \
  /usr/include/sys/reent.h /usr/include/_ansi.h /usr/include/sys/_types.h \
  /usr/include/sys/lock.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stddef.h \
  /usr/include/sys/string.h ../include/common.h /usr/include/stdio.h \
  /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stdarg.h \
  /usr/include/sys/types.h /usr/include/machine/_types.h \
  /usr/include/machine/types.h /usr/include/sys/features.h \
  /usr/include/cygwin/types.h /usr/include/sys/sysmacros.h \
  /usr/include/stdint.h /usr/include/endian.h /usr/include/sys/stdio.h \
  /usr/include/sys/cdefs.h /usr/include/errno.h /usr/include/sys/errno.h \
  ../include/char.h ../include/common.h ../include/char_base.h \
  ../include/version.h ../include/skill.h ../include/util.h \
  /usr/include/sys/time.h /usr/include/cygwin/sys_time.h \
  /usr/include/sys/select.h /usr/include/time.h \
  /usr/include/machine/time.h /usr/include/cygwin/time.h \
  /usr/include/signal.h /usr/include/sys/signal.h \
  /usr/include/cygwin/signal.h /usr/include/stdlib.h \
  /usr/include/machine/stdlib.h /usr/include/alloca.h \
  /usr/include/cygwin/stdlib.h /usr/include/cygwin/wait.h \
  ../include/title.h ../include/addressbook.h ../include/net.h \
  /usr/include/netinet/in.h /usr/include/cygwin/in.h \
  /usr/include/cygwin/socket.h /usr/include/asm/socket.h \
  /usr/include/cygwin/if.h /usr/include/sys/socket.h \
  /usr/include/features.h /usr/include/cygwin/sockios.h \
  /usr/include/cygwin/uio.h /usr/include/asm/byteorder.h \
  /usr/include/pthread.h /usr/include/sched.h ../include/char_data.h \
  ../include/item.h ../include/char.h ../include/char_base.h \
  ../include/object.h ../include/buf.h ../include/util.h \
  ../include/configfile.h ../include/readmap.h ../include/map_warppoint.h
